# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']


# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  leaderboard-compute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install -r .github/workflows/scripts/ci.requirements.txt


    - name: Run python script
      run: |
          python .github/workflows/scripts/minimal-leaderboard.py
    - name: Upload leaderboard
      uses: actions/upload-artifact@v4
      with:
        name: leaderboard
        path: leaderboard.json


  deploy:
    needs: leaderboard-compute
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site/VTikZ
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download leaderboard artifacts
        uses: actions/download-artifact@v4
        with:
          name: leaderboard
          path: site/VTikZ/src/assets/
        

      #node setup and deploy
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: 'site/VTikZ/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: 'site/VTikZ/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4